# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup_resize.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Resize(object):
    def setupUi(self, Resize):
        Resize.setObjectName("Resize")
        Resize.resize(340, 280)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Resize.sizePolicy().hasHeightForWidth())
        Resize.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(Resize)
        self.label.setGeometry(QtCore.QRect(20, 20, 171, 20))
        self.label.setObjectName("label")
        self.label_ImageSize = QtWidgets.QLabel(Resize)
        self.label_ImageSize.setGeometry(QtCore.QRect(240, 20, 171, 20))
        self.label_ImageSize.setObjectName("label_ImageSize")
        self.label_2 = QtWidgets.QLabel(Resize)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 51, 20))
        self.label_2.setObjectName("label_2")
        self.lineEditHeight = QtWidgets.QLineEdit(Resize)
        self.lineEditHeight.setGeometry(QtCore.QRect(190, 90, 113, 20))
        self.lineEditHeight.setText("")
        self.lineEditHeight.setObjectName("lineEditHeight")
        self.lineEditWidth = QtWidgets.QLineEdit(Resize)
        self.lineEditWidth.setGeometry(QtCore.QRect(190, 140, 113, 20))
        self.lineEditWidth.setText("")
        self.lineEditWidth.setObjectName("lineEditWidth")
        self.label_3 = QtWidgets.QLabel(Resize)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 51, 20))
        self.label_3.setObjectName("label_3")
        self.pushButton_Resize = QtWidgets.QPushButton(Resize)
        self.pushButton_Resize.setGeometry(QtCore.QRect(95, 210, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Resize.sizePolicy().hasHeightForWidth())
        self.pushButton_Resize.setSizePolicy(sizePolicy)
        self.pushButton_Resize.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_Resize.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_Resize.setObjectName("pushButton_Resize")

        self.retranslateUi(Resize)
        QtCore.QMetaObject.connectSlotsByName(Resize)

    def retranslateUi(self, Resize):
        _translate = QtCore.QCoreApplication.translate
        Resize.setWindowTitle(_translate("Resize", "Resizing"))
        self.label.setText(_translate("Resize", "Aktualny rozmiar zdjęcia"))
        self.label_ImageSize.setText(_translate("Resize", "Rozmiar aktualny"))
        self.label_2.setText(_translate("Resize", "Wysokość"))
        self.label_3.setText(_translate("Resize", "Szerokość"))
        self.pushButton_Resize.setText(_translate("Resize", "Resize"))
