# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup_noise.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Noise(object):
    def setupUi(self, Noise):
        Noise.setObjectName("Noise")
        Noise.resize(340, 280)
        self.pushButton_Noise = QtWidgets.QPushButton(Noise)
        self.pushButton_Noise.setGeometry(QtCore.QRect(95, 210, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Noise.sizePolicy().hasHeightForWidth())
        self.pushButton_Noise.setSizePolicy(sizePolicy)
        self.pushButton_Noise.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_Noise.setObjectName("pushButton_Noise")
        self.label = QtWidgets.QLabel(Noise)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 16))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Noise)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 77, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_Gauss = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_Gauss.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_Gauss.setObjectName("radioButton_Gauss")
        self.verticalLayout.addWidget(self.radioButton_Gauss)
        self.radioButton_Poisson = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_Poisson.setObjectName("radioButton_Poisson")
        self.verticalLayout.addWidget(self.radioButton_Poisson)
        self.radioButton_Speckle = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_Speckle.setObjectName("radioButton_Speckle")
        self.verticalLayout.addWidget(self.radioButton_Speckle)
        self.radioButton_SaltPepper = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_SaltPepper.setObjectName("radioButton_SaltPepper")
        self.verticalLayout.addWidget(self.radioButton_SaltPepper)
        self.horizontalSlider = QtWidgets.QSlider(Noise)
        self.horizontalSlider.setGeometry(QtCore.QRect(170, 80, 111, 21))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(250)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(Noise)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(170, 130, 111, 22))
        self.horizontalSlider_2.setMinimum(1)
        self.horizontalSlider_2.setMaximum(250)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_2 = QtWidgets.QLabel(Noise)
        self.label_2.setGeometry(QtCore.QRect(120, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Noise)
        self.label_3.setGeometry(QtCore.QRect(120, 130, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_Mean = QtWidgets.QLabel(Noise)
        self.label_Mean.setGeometry(QtCore.QRect(290, 80, 47, 13))
        self.label_Mean.setText("")
        self.label_Mean.setObjectName("label_Mean")
        self.label_Var = QtWidgets.QLabel(Noise)
        self.label_Var.setGeometry(QtCore.QRect(290, 130, 47, 13))
        self.label_Var.setText("")
        self.label_Var.setObjectName("label_Var")

        self.retranslateUi(Noise)
        self.horizontalSlider.sliderMoved['int'].connect(Noise.slider_change)
        self.horizontalSlider_2.sliderMoved['int'].connect(Noise.slider_change_2)
        QtCore.QMetaObject.connectSlotsByName(Noise)

    def retranslateUi(self, Noise):
        _translate = QtCore.QCoreApplication.translate
        Noise.setWindowTitle(_translate("Noise", "Zaszumianie"))
        self.pushButton_Noise.setText(_translate("Noise", "Wykonaj"))
        self.label.setText(_translate("Noise", "Wybierz szum:"))
        self.radioButton_Gauss.setText(_translate("Noise", "Gauss"))
        self.radioButton_Poisson.setText(_translate("Noise", "Poisson"))
        self.radioButton_Speckle.setText(_translate("Noise", "Speckle"))
        self.radioButton_SaltPepper.setText(_translate("Noise", "Salt&Pepper"))
        self.label_2.setText(_translate("Noise", "mean"))
        self.label_3.setText(_translate("Noise", "var"))
