# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup_model.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Model(object):
    def setupUi(self, Model):
        Model.setObjectName("Model")
        Model.resize(580, 525)
        self.textEdit = QtWidgets.QTextEdit(Model)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 561, 511))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Model)
        QtCore.QMetaObject.connectSlotsByName(Model)

    def retranslateUi(self, Model):
        _translate = QtCore.QCoreApplication.translate
        Model.setWindowTitle(_translate("Model", "Form"))
