# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup_rotation.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Rotation(object):
    def setupUi(self, Rotation):
        Rotation.setObjectName("Rotation")
        Rotation.resize(340, 280)
        self.pushButton_Rotation = QtWidgets.QPushButton(Rotation)
        self.pushButton_Rotation.setGeometry(QtCore.QRect(95, 210, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Rotation.sizePolicy().hasHeightForWidth())
        self.pushButton_Rotation.setSizePolicy(sizePolicy)
        self.pushButton_Rotation.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_Rotation.setObjectName("pushButton_Rotation")
        self.verticalLayoutWidget = QtWidgets.QWidget(Rotation)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 50, 61, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_90 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_90.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_90.setObjectName("radioButton_90")
        self.verticalLayout.addWidget(self.radioButton_90)
        self.radioButton_180 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_180.setObjectName("radioButton_180")
        self.verticalLayout.addWidget(self.radioButton_180)
        self.radioButton_270 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_270.setObjectName("radioButton_270")
        self.verticalLayout.addWidget(self.radioButton_270)
        self.label = QtWidgets.QLabel(Rotation)
        self.label.setGeometry(QtCore.QRect(120, 20, 101, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Rotation)
        QtCore.QMetaObject.connectSlotsByName(Rotation)

    def retranslateUi(self, Rotation):
        _translate = QtCore.QCoreApplication.translate
        Rotation.setWindowTitle(_translate("Rotation", "Rotacja"))
        self.pushButton_Rotation.setText(_translate("Rotation", "Wykonaj"))
        self.radioButton_90.setText(_translate("Rotation", "90"))
        self.radioButton_180.setText(_translate("Rotation", "180"))
        self.radioButton_270.setText(_translate("Rotation", "270"))
        self.label.setText(_translate("Rotation", "Kąt obrotu zdjęcia:"))
